### ISSUE TITLE
Browser CDN 

### ISSUE THREAD

**Issue by amchconsult** [dgknca/vue-multi-split-pane#1]
Can you show how to include in browser CDN as global?
thank you

**Comment by dgknca** [comment]
Hi @amchconsult Currently there is no browser support. I will add as soon as possible.

**Comment by amchconsult** [comment]
thank you

**Comment by amchconsult** [comment]
Hi,
I see you have done some updates. 
is it a component or use mode for browser global?
thank you

**Comment by dgknca** [comment]
Not yet. I were working on it and I took a break for a while because it bothered me that it was not working. But now I am determined to finish this job. I'll be working on it today and tomorrow. Thanks for triggering me :)

**Comment by dgknca** [comment]
This is it! Check the README https://github.com/dgknca/vue-multi-split-pane/commit/5397ae8d27b92000eeed53ff74f4fff976024d9b

**Comment by amchconsult** [comment]
I just tested.
It works perfect.
Thank you very much. Great component
